// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTEfwCoLm2nBMQar-29VsEk9endLVGTd4',
    appId: '1:362956281866:web:b19ff0800ca7faebee27f3',
    messagingSenderId: '362956281866',
    projectId: 'zmall-184809',
    authDomain: 'zmall-184809.firebaseapp.com',
    databaseURL: 'https://zmall-184809.firebaseio.com',
    storageBucket: 'zmall-184809.appspot.com',
    measurementId: 'G-NXGGGYL28Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFfRtPeakrhsHOxOaZOYpPQM8klHC6Y80',
    appId: '1:362956281866:android:4653b7a0c64f4f10',
    messagingSenderId: '362956281866',
    projectId: 'zmall-184809',
    databaseURL: 'https://zmall-184809.firebaseio.com',
    storageBucket: 'zmall-184809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAgZScAJfUHxahi_n4OpuI8HrTHVlirJk',
    appId: '1:362956281866:ios:4653b7a0c64f4f10',
    messagingSenderId: '362956281866',
    projectId: 'zmall-184809',
    databaseURL: 'https://zmall-184809.firebaseio.com',
    storageBucket: 'zmall-184809.appspot.com',
    androidClientId: '362956281866-1ss42kupu9momch6ou2qpk7ppf6smlot.apps.googleusercontent.com',
    iosClientId: '362956281866-4pn66vt8g3ptaa5hmqjnhhni91gb9k5n.apps.googleusercontent.com',
    iosBundleId: 'com.zmall.user',
  );
}
