const countries = {
  "Qatar": "packages/country_code_picker/flags/qa.png",
  "Ecuador": "packages/country_code_picker/flags/ec.png",
  "Senegal": "packages/country_code_picker/flags/sn.png",
  "Netherlands": "packages/country_code_picker/flags/nl.png",
  "England": "packages/country_code_picker/flags/gb-eng.png",
  "Iran": "packages/country_code_picker/flags/ir.png",
  "USA": "packages/country_code_picker/flags/us.png",
  "Wales": "packages/country_code_picker/flags/gb-wls.png",
  "Argentina": "packages/country_code_picker/flags/ar.png",
  "Saudi Arabia": "packages/country_code_picker/flags/sa.png",
  "Mexico": "packages/country_code_picker/flags/mx.png",
  "Poland": "packages/country_code_picker/flags/pl.png",
  "France": "packages/country_code_picker/flags/fr.png",
  "Australia": "packages/country_code_picker/flags/au.png",
  "Denmark": "packages/country_code_picker/flags/dk.png",
  "Tunisia": "packages/country_code_picker/flags/tn.png",
  "Spain": "packages/country_code_picker/flags/es.png",
  "Costa Rica": "packages/country_code_picker/flags/cr.png",
  "Germany": "packages/country_code_picker/flags/de.png",
  "Japan": "packages/country_code_picker/flags/jp.png",
  "Belgium": "packages/country_code_picker/flags/be.png",
  "Canada": "packages/country_code_picker/flags/ca.png",
  "Morocco": "packages/country_code_picker/flags/ma.png",
  "Croatia": "packages/country_code_picker/flags/hr.png",
  "Brazil": "packages/country_code_picker/flags/br.png",
  "Serbia": "packages/country_code_picker/flags/rs.png",
  "Switzerland": "packages/country_code_picker/flags/ch.png",
  "Cameroon": "packages/country_code_picker/flags/cm.png",
  "Portugal": "packages/country_code_picker/flags/pt.png",
  "Ghana": "packages/country_code_picker/flags/gh.png",
  "Uruguay": "packages/country_code_picker/flags/uy.png",
  "South Korea": "packages/country_code_picker/flags/kr.png",
};

const game = [
  {
    "id": "12345566",
    "type": "Game Week 1",
    "home_team": "CHE",
    "away_team": "LIV",
    "time": "Sunday August 13, 2023 18:30",
    "stadium": "Stamford Bridge",
    "is_finished": false,
    "home_score": 0,
    "away_score": 0,
    "home_win": false,
    "away_win": false,
    "draw": false,
    "penalties": false,
    "penalty_score": "",
  },
  {
    "id": "12345566",
    "type": "Game Week 2",
    "home_team": "TOT",
    "away_team": "MUN",
    "time": "Saturday August 19, 2023 19:30",
    "stadium": "Tottenham Hotspur Stadium",
    "is_finished": false,
    "home_score": 0,
    "away_score": 0,
    "home_win": false,
    "away_win": false,
    "draw": false,
    "penalties": false,
    "penalty_score": "",
  },
  {
    "id": "12345566",
    "type": "Game Week 3",
    "home_team": "NEW",
    "away_team": "LIV",
    "time": "Sunday 27 August 18:30",
    "stadium": "St. James' Park",
    "is_finished": false,
    "home_score": 0,
    "away_score": 0,
    "home_win": false,
    "away_win": false,
    "draw": true,
    "penalties": false,
    "penalty_score": "",
  },
  {
    "id": "12345566",
    "type": "Game Week 4",
    "home_team": "ARS",
    "away_team": "MUN",
    "time": "Sunday, September 3 2023 18:30",
    "stadium": "Emirates Stadium",
    "is_finished": false,
    "home_score":0,
    "away_score": 0,
    "home_win": false,
    "away_win": false,
    "draw": false,
    "penalties": false,
    "penalty_score": "",
  },
];
